# Heart Disease Prediction

In [3]:
import sys
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import keras


In [4]:
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix

### 1. Importing the Dataset

The dataset is available through the University of California, Irvine Machine learning repository. Here is the URL:

http:////archive.ics.uci.edu/ml/datasets/Heart+Disease

This dataset contains patient data concerning heart disease diagnosis that was collected at several locations around the world. There are 76 attributes, including age, sex, resting blood pressure, cholestoral levels, echocardiogram data, exercise habits, and many others. To data, all published studies using this data focus on a subset of 14 attributes - so we will do the same. More specifically, we will use the data collected at the Cleveland Clinic Foundation.

To import the necessary data, we will use pandas' built in read_csv() function. Let's get started!

In [5]:
# import the heart disease dataset
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

# the names will be the names of each column in our pandas DataFrame
names = ['age',
        'sex',
        'cp',
        'trestbps',
        'chol',
        'fbs',
        'restecg',
        'thalach',
        'exang',
        'oldpeak',
        'slope',
        'ca',
        'thal',
        'class']

# read the csv
cleveland = pd.read_csv(url, names=names)

In [6]:
# print the shape of the DataFrame, so we can see how many examples we have
print ('format(cleveland.shape')
print (cleveland.loc[1])

format(cleveland.shape
age          67.0
sex           1.0
cp            4.0
trestbps    160.0
chol        286.0
fbs           0.0
restecg       2.0
thalach     108.0
exang         1.0
oldpeak       1.5
slope         2.0
ca            3.0
thal          3.0
class           2
Name: 1, dtype: object


In [7]:
# print the last twenty or so data points
cleveland.loc[280:]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
280  57.0  1.0  4.0     110.0  335.0  0.0      0.0    143.0    1.0      3.0   
281  47.0  1.0  3.0     130.0  253.0  0.0      0.0    179.0    0.0      0.0   
282  55.0  0.0  4.0     128.0  205.0  0.0      1.0    130.0    1.0      2.0   
283  35.0  1.0  2.0     122.0  192.0  0.0      0.0    174.0    0.0      0.0   
284  61.0  1.0  4.0     148.0  203.0  0.0      0.0    161.0    0.0      0.0   
285  58.0  1.0  4.0     114.0  318.0  0.0      1.0    140.0    0.0      4.4   
286  58.0  0.0  4.0     170.0  225.0  1.0      2.0    146.0    1.0      2.8   
287  58.0  1.0  2.0     125.0  220.0  0.0      0.0    144.0    0.0      0.4   
288  56.0  1.0  2.0     130.0  221.0  0.0      2.0    163.0    0.0      0.0   
289  56.0  1.0  2.0     120.0  240.0  0.0      0.0    169.0    0.0      0.0   
290  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
291  55.0  0.0  2.0     132.0  342.0  0.0      0.0    166.0    0.0      1.2   
292  44.0  1.0  4.0     120.0  169.0  0.0      0.0    144.0    1.0      2.8   
293  63.0  1.0  4.0     140.0  187.0  0.0      2.0    144.0    1.0      4.0   
294  63.0  0.0  4.0     124.0  197.0  0.0      0.0    136.0    1.0      0.0   
295  41.0  1.0  2.0     120.0  157.0  0.0      0.0    182.0    0.0      0.0   
296  59.0  1.0  4.0     164.0  176.0  1.0      2.0     90.0    0.0      1.0   
297  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0      0.2   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   
302  38.0  1.0  3.0     138.0  175.0  0.0      0.0    173.0    0.0      0.0   

     slope   ca thal  class  
280    2.0  1.0  7.0      2  
281    1.0  0.0  3.0      0  
282    2.0  1.0  7.0      3  
283    1.0  0.0  3.0      0  
284    1.0  1.0  7.0      2  
285    3.0  3.0  6.0      4  
286    2.0  2.0  6.0      2  
287    2.0    ?  7.0      0  
288    1.0  0.0  7.0      0  
289    3.0  0.0  3.0      0  
290    2.0  0.0  7.0      1  
291    1.0  0.0  3.0      0  
292    3.0  0.0  6.0      2  
293    1.0  2.0  7.0      2  
294    2.0  0.0  3.0      1  
295    1.0  0.0  3.0      0  
296    2.0  2.0  6.0      3  
297    2.0  0.0  7.0      1  
298    2.0  0.0  7.0      1  
299    2.0  2.0  7.0      2  
300    2.0  1.0  7.0      3  
301    2.0  1.0  3.0      1  
302    1.0    ?  3.0      0

In [8]:
# remove missing data (indicated with a "?")
data = cleveland[~cleveland.isin(['?'])]
data.loc[280:]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
280  57.0  1.0  4.0     110.0  335.0  0.0      0.0    143.0    1.0      3.0   
281  47.0  1.0  3.0     130.0  253.0  0.0      0.0    179.0    0.0      0.0   
282  55.0  0.0  4.0     128.0  205.0  0.0      1.0    130.0    1.0      2.0   
283  35.0  1.0  2.0     122.0  192.0  0.0      0.0    174.0    0.0      0.0   
284  61.0  1.0  4.0     148.0  203.0  0.0      0.0    161.0    0.0      0.0   
285  58.0  1.0  4.0     114.0  318.0  0.0      1.0    140.0    0.0      4.4   
286  58.0  0.0  4.0     170.0  225.0  1.0      2.0    146.0    1.0      2.8   
287  58.0  1.0  2.0     125.0  220.0  0.0      0.0    144.0    0.0      0.4   
288  56.0  1.0  2.0     130.0  221.0  0.0      2.0    163.0    0.0      0.0   
289  56.0  1.0  2.0     120.0  240.0  0.0      0.0    169.0    0.0      0.0   
290  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
291  55.0  0.0  2.0     132.0  342.0  0.0      0.0    166.0    0.0      1.2   
292  44.0  1.0  4.0     120.0  169.0  0.0      0.0    144.0    1.0      2.8   
293  63.0  1.0  4.0     140.0  187.0  0.0      2.0    144.0    1.0      4.0   
294  63.0  0.0  4.0     124.0  197.0  0.0      0.0    136.0    1.0      0.0   
295  41.0  1.0  2.0     120.0  157.0  0.0      0.0    182.0    0.0      0.0   
296  59.0  1.0  4.0     164.0  176.0  1.0      2.0     90.0    0.0      1.0   
297  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0      0.2   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   
302  38.0  1.0  3.0     138.0  175.0  0.0      0.0    173.0    0.0      0.0   

     slope   ca thal  class  
280    2.0  1.0  7.0      2  
281    1.0  0.0  3.0      0  
282    2.0  1.0  7.0      3  
283    1.0  0.0  3.0      0  
284    1.0  1.0  7.0      2  
285    3.0  3.0  6.0      4  
286    2.0  2.0  6.0      2  
287    2.0  NaN  7.0      0  
288    1.0  0.0  7.0      0  
289    3.0  0.0  3.0      0  
290    2.0  0.0  7.0      1  
291    1.0  0.0  3.0      0  
292    3.0  0.0  6.0      2  
293    1.0  2.0  7.0      2  
294    2.0  0.0  3.0      1  
295    1.0  0.0  3.0      0  
296    2.0  2.0  6.0      3  
297    2.0  0.0  7.0      1  
298    2.0  0.0  7.0      1  
299    2.0  2.0  7.0      2  
300    2.0  1.0  7.0      3  
301    2.0  1.0  3.0      1  
302    1.0  NaN  3.0      0

In [9]:
# drop rows with NaN values from DataFrame
data = data.dropna(axis=0)
data.loc[280:]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
280  57.0  1.0  4.0     110.0  335.0  0.0      0.0    143.0    1.0      3.0   
281  47.0  1.0  3.0     130.0  253.0  0.0      0.0    179.0    0.0      0.0   
282  55.0  0.0  4.0     128.0  205.0  0.0      1.0    130.0    1.0      2.0   
283  35.0  1.0  2.0     122.0  192.0  0.0      0.0    174.0    0.0      0.0   
284  61.0  1.0  4.0     148.0  203.0  0.0      0.0    161.0    0.0      0.0   
285  58.0  1.0  4.0     114.0  318.0  0.0      1.0    140.0    0.0      4.4   
286  58.0  0.0  4.0     170.0  225.0  1.0      2.0    146.0    1.0      2.8   
288  56.0  1.0  2.0     130.0  221.0  0.0      2.0    163.0    0.0      0.0   
289  56.0  1.0  2.0     120.0  240.0  0.0      0.0    169.0    0.0      0.0   
290  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
291  55.0  0.0  2.0     132.0  342.0  0.0      0.0    166.0    0.0      1.2   
292  44.0  1.0  4.0     120.0  169.0  0.0      0.0    144.0    1.0      2.8   
293  63.0  1.0  4.0     140.0  187.0  0.0      2.0    144.0    1.0      4.0   
294  63.0  0.0  4.0     124.0  197.0  0.0      0.0    136.0    1.0      0.0   
295  41.0  1.0  2.0     120.0  157.0  0.0      0.0    182.0    0.0      0.0   
296  59.0  1.0  4.0     164.0  176.0  1.0      2.0     90.0    0.0      1.0   
297  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0      0.2   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0      1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0      3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0      1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0      0.0   

     slope   ca thal  class  
280    2.0  1.0  7.0      2  
281    1.0  0.0  3.0      0  
282    2.0  1.0  7.0      3  
283    1.0  0.0  3.0      0  
284    1.0  1.0  7.0      2  
285    3.0  3.0  6.0      4  
286    2.0  2.0  6.0      2  
288    1.0  0.0  7.0      0  
289    3.0  0.0  3.0      0  
290    2.0  0.0  7.0      1  
291    1.0  0.0  3.0      0  
292    3.0  0.0  6.0      2  
293    1.0  2.0  7.0      2  
294    2.0  0.0  3.0      1  
295    1.0  0.0  3.0      0  
296    2.0  2.0  6.0      3  
297    2.0  0.0  7.0      1  
298    2.0  0.0  7.0      1  
299    2.0  2.0  7.0      2  
300    2.0  1.0  7.0      3  
301    2.0  1.0  3.0      1

In [10]:
# print the shape and data type of the dataframe
print (data.shape)
print (data.dtypes)

(297, 14)
age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca           object
thal         object
class         int64
dtype: object


In [11]:
# transform data to numeric to enable further analysis
data = data.apply(pd.to_numeric)
data.dtypes

age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca          float64
thal        float64
class         int64
dtype: object

In [12]:
# print data characteristics, usings pandas built-in describe() function
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  297.000000  297.000000  297.000000  297.000000  297.000000  297.000000   
mean    54.542088    0.676768    3.158249  131.693603  247.350168    0.144781   
std      9.049736    0.468500    0.964859   17.762806   51.997583    0.352474   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  243.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  276.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  297.000000  297.000000  297.000000  297.000000  297.000000  297.000000   
mean     0.996633  149.599327    0.326599    1.055556    1.602694    0.676768   
std      0.994914   22.941562    0.469761    1.166123    0.618187    0.938965   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  133.000000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

             thal       class  
count  297.000000  297.000000  
mean     4.730640    0.946128  
std      1.938629    1.234551  
min      3.000000    0.000000  
25%      3.000000    0.000000  
50%      3.000000    0.000000  
75%      7.000000    2.000000  
max      7.000000    4.000000

### 2. Create Training and Testing Datasets

Now that we have preprocessed the data appropriately, we can split it into training and testings datasets. We will use Sklearn's train_test_split() function to generate a training dataset (80 percent of the total data) and testing dataset (20 percent of the total data). 

Furthermore, the class values in this dataset contain multiple types of heart disease with values ranging from 0 (healthy) to 4 (severe heart disease). Consequently, we will need to convert our class data to categorical labels. For example, the label 2 will become [0, 0, 1, 0, 0]. 

In [20]:
# create X and Y datasets for training
from sklearn import model_selection
z=data.drop('class',axis=1)
X = np.array(z)
y = np.array(data['class'])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.2)

In [23]:
# convert the data to categorical labels
from tensorflow.keras.utils import to_categorical

Y_train = to_categorical(y_train, num_classes=None)
Y_test = to_categorical(y_test, num_classes=None)
print (Y_train.shape)
print (Y_train[:10])

(237, 5)
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]


### 3. Building and Training the Neural Network

Now that we have our data fully processed and split into training and testing datasets, we can begin building a neural network to solve this classification problem. Using keras, we will define a simple neural network with one hidden layer. Since this is a categorical classification problem, we will use a softmax activation function in the final layer of our network and a categorical_crossentropy loss during our training phase.

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# define a function to build the keras model
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(8, input_dim=13, kernel_initializer='normal', activation='relu'))
    model.add(Dense(4, kernel_initializer='normal', activation='relu'))
    model.add(Dense(5, activation='softmax'))
    
    # compile model
    adam = Adam(learning_rate=0.001)
    model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

model = create_model()

print(model.summary())


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │           112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            25 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (692.00 B)

 Trainable params: 173 (692.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [26]:
# fit the model to the training data
model.fit(X_train, Y_train, epochs=100, batch_size=10, verbose = 1)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3642 - loss: 1.5759   
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 0.5142 - loss: 1.3695
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5218 - loss: 1.3434 
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.5594 - loss: 1.2564
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5920 - loss: 1.1745 
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5304 - loss: 1.2649 
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5865 - loss: 1.1823 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5478 - loss: 1.2647 
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5605 - loss: 1.2217 
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5302 - loss: 1.2512 
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5616 - loss: 1.1828 
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/s

### 4. Improving Results - A Binary Classification Problem

Although we achieved promising results, we still have a fairly large error. This could be because it is very difficult to distinguish between the different severity levels of heart disease (classes 1 - 4). Let's simplify the problem by converting the data to a binary classification problem - heart disease or no heart disease.

In [27]:
# convert into binary classification problem - heart disease or no heart disease
Y_train_binary = y_train.copy()
Y_test_binary = y_test.copy()

Y_train_binary[Y_train_binary > 0] = 1
Y_test_binary[Y_test_binary > 0] = 1

print (Y_train_binary[:20])

[0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0]


In [30]:
# define a new keras model for binary classification
def create_binary_model():
    # create model
    model = Sequential()
    model.add(Dense(8, input_dim=13, kernel_initializer='normal', activation='relu'))
    model.add(Dense(4, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    
    # Compile model
    adam = Adam(learning_rate=0.001)
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

model = create_binary_model()

print(model.summary())

c:\Users\wwwst\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 8)              │           112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 153 (612.00 B)

 Trainable params: 153 (612.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [31]:
# fit the binary model on the training data
model.fit(X_train, Y_train_binary, epochs=100, batch_size=10, verbose = 1)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4936 - loss: 0.7173   
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5575 - loss: 0.6923 
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.5883 - loss: 0.6909
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6292 - loss: 0.6898
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.6476 - loss: 0.6867
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6668 - loss: 0.6864
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5621 - loss: 0.6868 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6342 - loss: 0.6841
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5984 - loss: 0.6779 
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7720 - loss: 0.6699
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7431 - loss: 0.6680 
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 853

### 5. Results and Metrics

The accuracy results we have been seeing are for the training data, but what about the testing dataset? If our model's cannot generalize to data that wasn't used to train them, they won't provide any utility. 

Let's test the performance of both our categorical model and binary model.  To do this, we will make predictions on the training dataset and calculate performance metrics using Sklearn.

In [32]:
# generate classification report using predictions for categorical model
from sklearn.metrics import classification_report, accuracy_score

categorical_pred = np.argmax(model.predict(X_test), axis=1)

print('Results for Categorical Model')
print(accuracy_score(y_test, categorical_pred))
print(classification_report(y_test, categorical_pred))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Results for Categorical Model
0.48333333333333334
              precision    recall  f1-score   support

           0       0.48      1.00      0.65        29
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00        10
           3       0.00      0.00      0.00         7
           4       0.00      0.00      0.00         4

    accuracy                           0.48        60
   macro avg       0.10      0.20      0.13        60
weighted avg       0.23      0.48      0.31        60



c:\Users\wwwst\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\wwwst\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\wwwst\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [34]:
# generate classification report using predictions for binary model 
binary_pred = np.round(model.predict(X_test)).astype(int)

print('Results for Binary Model')
print(accuracy_score(Y_test_binary, binary_pred))
print(classification_report(Y_test_binary, binary_pred))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step  
Results for Binary Model
0.7333333333333333
              precision    recall  f1-score   support

           0       0.68      0.86      0.76        29
           1       0.83      0.61      0.70        31

    accuracy                           0.73        60
   macro avg       0.75      0.74      0.73        60
weighted avg       0.75      0.73      0.73        60

